#ifndef HT_KEYWORDS_INCLUDED
#define HT_KEYWORDS_INCLUDED

// Shade
#pragma shader_feature_local_fragment _HT_SHADE_MODE_POS_AND_BLUR _HT_SHADE_MODE_RAMP

#pragma shader_feature_local_fragment _HT_USE_FIRST_SHADE
#pragma shader_feature_local_fragment _HT_USE_FIRST_SHADE_MAP
#pragma shader_feature_local_fragment _HT_USE_EX_FIRST_SHADE
#pragma shader_feature_local_fragment _HT_USE_SECOND_SHADE
#pragma shader_feature_local_fragment _HT_USE_SECOND_SHADE_MAP

#pragma shader_feature_local_fragment _HT_USE_RAMP_SHADE

#pragma shader_feature_local_fragment _HT_USE_SHADE_CONTROL_MAP

// Rim Light
#pragma shader_feature_local_fragment _HT_USE_RIM_LIGHT
#pragma shader_feature_local_fragment _HT_USE_RIM_LIGHT_MAP

// Emission
#pragma shader_feature_local_fragment _HT_USE_EMISSION
#pragma shader_feature_local_fragment _HT_USE_EMISSION_MAP
#pragma shader_feature_local_fragment _HT_OVERRIDE_EMISSION_COLOR

// MatCap
#pragma shader_feature_local_fragment _HT_USE_MAT_CAP
#pragma shader_feature_local_fragment _HT_USE_MAT_CAP_MASK

// Normal Override
// Note: Not fragment-only because it needs to work in vertex shader for correct GI
#pragma shader_feature_local _HT_USE_NORMAL_OVERRIDE

// Direct Lighting
#pragma shader_feature_local_fragment _HT_RECEIVE_MAIN_LIGHT_DIFFUSE
#pragma shader_feature_local_fragment _HT_RECEIVE_MAIN_LIGHT_SPECULAR
#pragma shader_feature_local_fragment _HT_RECEIVE_ADDITIONAL_LIGHTS_DIFFUSE
#pragma shader_feature_local_fragment _HT_RECEIVE_ADDITIONAL_LIGHTS_SPECULAR

// Indirect Lighting(GI)
#pragma shader_feature_local_fragment _HT_RECEIVE_INDIRECT_DIFFUSE
#pragma shader_feature_local_fragment _HT_RECEIVE_INDIRECT_SPECULAR
#pragma shader_feature_local_fragment _HT_RECEIVE_SSAO
#pragma shader_feature_local_fragment _HT_USE_SSAO_MASK

#endif
