#ifndef HT_PREDEFINE_INCLUDED
#define HT_PREDEFINE_INCLUDED

#define NOT(boolValue) !(boolValue)

#define ONE 1

#if defined(_HT_RECEIVE_MAIN_LIGHT_DIFFUSE) || defined(_HT_RECEIVE_MAIN_LIGHT_SPECULAR)
    #define _HT_RECEIVE_MAIN_LIGHT
#endif

#if defined(_HT_RECEIVE_ADDITIONAL_LIGHTS_DIFFUSE) || defined(_HT_RECEIVE_ADDITIONAL_LIGHTS_SPECULAR)
    #define _HT_RECEIVE_ADDITIONAL_LIGHTS
#endif

#if defined(_HT_RECEIVE_INDIRECT_DIFFUSE) || defined(_HT_RECEIVE_INDIRECT_SPECULAR)
    #define _HT_RECEIVE_INDIRECT
#endif

#endif
