#ifndef HUM_TOON_KEYWORDS_INCLUDED
#define HUM_TOON_KEYWORDS_INCLUDED

// Shade
#pragma shader_feature_local_fragment _USE_FIRST_SHADE
#pragma shader_feature_local_fragment _USE_FIRST_SHADE_MAP
#pragma shader_feature_local_fragment _USE_EX_FIRST_SHADE
#pragma shader_feature_local_fragment _USE_SECOND_SHADE
#pragma shader_feature_local_fragment _USE_SECOND_SHADE_MAP

// MatCap
#pragma shader_feature_local_fragment _USE_MAT_CAP

#endif
