#ifndef HUM_TOON_KEYWORDS_INCLUDED
#define HUM_TOON_KEYWORDS_INCLUDED

// Shade
#pragma shader_feature_local_fragment _HUM_USE_FIRST_SHADE
#pragma shader_feature_local_fragment _HUM_USE_FIRST_SHADE_MAP
#pragma shader_feature_local_fragment _HUM_USE_EX_FIRST_SHADE
#pragma shader_feature_local_fragment _HUM_USE_SECOND_SHADE
#pragma shader_feature_local_fragment _HUM_USE_SECOND_SHADE_MAP

// RimLight
#pragma shader_feature_local_fragment _HUM_USE_RIM_LIGHT

// MatCap
#pragma shader_feature_local_fragment _HUM_USE_MAT_CAP

#endif
